/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PriceRange = {
  minPrice?: number;
  maxPrice?: number;
  currency?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
};

export type NarrativeBlock = {
  _type: "narrativeBlock";
  label?: string;
  body?: string;
};

export type Metric = {
  _type: "metric";
  value?: string;
  label?: string;
};

export type IconLabel = {
  _type: "iconLabel";
  icon?: "Activity" | "ClipboardList" | "Cog" | "Factory" | "GitCompareArrows" | "Layers" | "LineChart" | "Map" | "Plug" | "Repeat" | "Search" | "Workflow" | "Gauge" | "ShieldCheck" | "Timer" | "Users";
  label?: string;
};

export type IconFeature = {
  _type: "iconFeature";
  icon?: "Activity" | "ClipboardList" | "Cog" | "Factory" | "GitCompareArrows" | "Layers" | "LineChart" | "Map" | "Plug" | "Repeat" | "Search" | "Workflow" | "Gauge" | "ShieldCheck" | "Timer" | "Users";
  title?: string;
  description?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "contentImage";
  _key: string;
}>;

export type CtaSection = {
  _type: "ctaSection";
  headline?: string;
  headlineAccent?: string;
  body?: string;
  emailPrompt?: string;
};

export type FaqSection = {
  _type: "faqSection";
  eyebrow?: string;
  heading?: string;
  questions?: Array<{
    _key: string;
  } & FaqItem>;
};

export type CaseStudySection = {
  _type: "caseStudySection";
  eyebrow?: string;
  heading?: string;
  lede?: string;
  disclaimer?: string;
  blocks?: Array<{
    _key: string;
  } & NarrativeBlock>;
  metrics?: Array<{
    _key: string;
  } & Metric>;
};

export type AssessmentSection = {
  _type: "assessmentSection";
  eyebrow?: string;
  heading?: string;
  lede?: string;
  price?: string;
  priceNote?: string;
  deliverablesHeading?: string;
  deliverables?: Array<string>;
  outcomeHeading?: string;
  outcome?: string;
  commitmentHeadline?: string;
  commitmentBody?: string;
  priceRange?: PriceRange;
};

export type ProcessSection = {
  _type: "processSection";
  eyebrow?: string;
  heading?: string;
  lede?: string;
  steps?: Array<{
    _key: string;
  } & IconFeature>;
};

export type DifferentiatorsSection = {
  _type: "differentiatorsSection";
  eyebrow?: string;
  headingLines?: Array<string>;
  headingAccent?: string;
  body?: Array<string>;
  differentiators?: Array<{
    _key: string;
  } & IconLabel>;
};

export type IndustriesSection = {
  _type: "industriesSection";
  eyebrow?: string;
  heading?: string;
  industries?: Array<string>;
};

export type CapabilitiesSection = {
  _type: "capabilitiesSection";
  eyebrow?: string;
  heading?: string;
  lede?: string;
  capabilities?: Array<{
    _key: string;
  } & IconFeature>;
};

export type ProblemSection = {
  _type: "problemSection";
  eyebrow?: string;
  heading?: string;
  lede?: string;
  symptoms?: Array<string>;
  diagnosis?: string;
  diagnosisAccent?: string;
};

export type HeroSection = {
  _type: "heroSection";
  badge?: string;
  headline?: string;
  headlineAccent?: string;
  lede?: string;
  secondaryAction?: NavLink;
  trustPoints?: Array<string>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoCaption?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  publishedAt?: string;
  author?: AuthorReference;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading?: string;
  lede?: string;
  emptyStateMessage?: string;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroSection;
  problem?: ProblemSection;
  capabilities?: CapabilitiesSection;
  industries?: IndustriesSection;
  differentiators?: DifferentiatorsSection;
  process?: ProcessSection;
  assessment?: AssessmentSection;
  caseStudy?: CaseStudySection;
  faq?: FaqSection;
  closingCta?: CtaSection;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
  tagline?: string;
  positioning?: string;
  keywords?: Array<string>;
  email?: string;
  schedulingUrl?: string;
  ctaLabel?: string;
  ctaLabelShort?: string;
  serviceTypes?: Array<string>;
  navLinks?: Array<{
    _key: string;
  } & NavLink>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = PriceRange | SanityImageAssetReference | Seo | NavLink | NarrativeBlock | Metric | IconLabel | IconFeature | FaqItem | BlockContent | CtaSection | FaqSection | CaseStudySection | AssessmentSection | ProcessSection | DifferentiatorsSection | IndustriesSection | CapabilitiesSection | ProblemSection | HeroSection | Category | Slug | AuthorReference | CategoryReference | Post | Author | SanityImageCrop | SanityImageHotspot | BlogPage | HomePage | SiteSettings | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    url,    email,    tagline,    positioning,    keywords,    schedulingUrl,    ctaLabel,    ctaLabelShort,    serviceTypes,    navLinks[]{ _key, label, href }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string | null;
  url: string | null;
  email: string | null;
  tagline: string | null;
  positioning: string | null;
  keywords: Array<string> | null;
  schedulingUrl: string | null;
  ctaLabel: string | null;
  ctaLabelShort: string | null;
  serviceTypes: Array<string> | null;
  navLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    hero{      badge,      headline,      headlineAccent,      lede,      secondaryAction{ label, href },      trustPoints,      photo{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },      photoCaption    },    problem{      eyebrow,      heading,      lede,      symptoms,      diagnosis,      diagnosisAccent    },    capabilities{      eyebrow,      heading,      lede,      capabilities[]{ _key, icon, title, description }    },    industries{      eyebrow,      heading,      industries    },    differentiators{      eyebrow,      headingLines,      headingAccent,      body,      differentiators[]{ _key, icon, label }    },    process{      eyebrow,      heading,      lede,      steps[]{ _key, icon, title, description }    },    assessment{      eyebrow,      heading,      lede,      price,      priceNote,      deliverablesHeading,      deliverables,      outcomeHeading,      outcome,      commitmentHeadline,      commitmentBody,      priceRange{ minPrice, maxPrice, currency }    },    caseStudy{      eyebrow,      heading,      lede,      disclaimer,      blocks[]{ _key, label, body },      metrics[]{ _key, value, label }    },    faq{      eyebrow,      heading,      questions[]{ _key, question, answer }    },    closingCta{      headline,      headlineAccent,      body,      emailPrompt    },    seo{      metaTitle,      metaDescription,      noIndex,      ogImage{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio }    }  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    badge: string | null;
    headline: string | null;
    headlineAccent: string | null;
    lede: string | null;
    secondaryAction: {
      label: string | null;
      href: string | null;
    } | null;
    trustPoints: Array<string> | null;
    photo: {
      alt: string | null;
      asset: SanityImageAssetReference | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
    photoCaption: string | null;
  } | null;
  problem: {
    eyebrow: string | null;
    heading: string | null;
    lede: string | null;
    symptoms: Array<string> | null;
    diagnosis: string | null;
    diagnosisAccent: string | null;
  } | null;
  capabilities: {
    eyebrow: string | null;
    heading: string | null;
    lede: string | null;
    capabilities: Array<{
      _key: string;
      icon: "Activity" | "ClipboardList" | "Cog" | "Factory" | "Gauge" | "GitCompareArrows" | "Layers" | "LineChart" | "Map" | "Plug" | "Repeat" | "Search" | "ShieldCheck" | "Timer" | "Users" | "Workflow" | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  industries: {
    eyebrow: string | null;
    heading: string | null;
    industries: Array<string> | null;
  } | null;
  differentiators: {
    eyebrow: string | null;
    headingLines: Array<string> | null;
    headingAccent: string | null;
    body: Array<string> | null;
    differentiators: Array<{
      _key: string;
      icon: "Activity" | "ClipboardList" | "Cog" | "Factory" | "Gauge" | "GitCompareArrows" | "Layers" | "LineChart" | "Map" | "Plug" | "Repeat" | "Search" | "ShieldCheck" | "Timer" | "Users" | "Workflow" | null;
      label: string | null;
    }> | null;
  } | null;
  process: {
    eyebrow: string | null;
    heading: string | null;
    lede: string | null;
    steps: Array<{
      _key: string;
      icon: "Activity" | "ClipboardList" | "Cog" | "Factory" | "Gauge" | "GitCompareArrows" | "Layers" | "LineChart" | "Map" | "Plug" | "Repeat" | "Search" | "ShieldCheck" | "Timer" | "Users" | "Workflow" | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  assessment: {
    eyebrow: string | null;
    heading: string | null;
    lede: string | null;
    price: string | null;
    priceNote: string | null;
    deliverablesHeading: string | null;
    deliverables: Array<string> | null;
    outcomeHeading: string | null;
    outcome: string | null;
    commitmentHeadline: string | null;
    commitmentBody: string | null;
    priceRange: {
      minPrice: number | null;
      maxPrice: number | null;
      currency: string | null;
    } | null;
  } | null;
  caseStudy: {
    eyebrow: string | null;
    heading: string | null;
    lede: string | null;
    disclaimer: string | null;
    blocks: Array<{
      _key: string;
      label: string | null;
      body: string | null;
    }> | null;
    metrics: Array<{
      _key: string;
      value: string | null;
      label: string | null;
    }> | null;
  } | null;
  faq: {
    eyebrow: string | null;
    heading: string | null;
    questions: Array<{
      _key: string;
      question: string | null;
      answer: string | null;
    }> | null;
  } | null;
  closingCta: {
    headline: string | null;
    headlineAccent: string | null;
    body: string | null;
    emailPrompt: string | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    ogImage: {
      alt: string | null;
      asset: SanityImageAssetReference | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
} | null;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: BLOG_PAGE_QUERY
// Query: *[_type == "blogPage" && _id == "blogPage"][0]{    eyebrow,    heading,    lede,    emptyStateMessage,    seo{      metaTitle,      metaDescription,      noIndex,      ogImage{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio }    }  }
export type BLOG_PAGE_QUERY_RESULT = {
  eyebrow: string | null;
  heading: string | null;
  lede: string | null;
  emptyStateMessage: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    ogImage: {
      alt: string | null;
      asset: SanityImageAssetReference | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
} | null;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: POSTS_INDEX_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now()]    | order(publishedAt desc){      _id,      title,      "slug": slug.current,      excerpt,      publishedAt,      coverImage{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },      author->{ name, role },      categories[]->{ _id, title, "slug": slug.current }    }
export type POSTS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
  author: {
    name: string | null;
    role: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: POST_DETAIL_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    coverImage{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio },    body[]{      ...,      _type == "contentImage" => {        alt,        caption,        asset,        "lqip": asset->metadata.lqip,        "aspectRatio": asset->metadata.dimensions.aspectRatio      },      markDefs[]{ ..., _type == "link" => { href } }    },    author->{ name, role, image{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio } },    categories[]->{ _id, title, "slug": slug.current },    seo{      metaTitle,      metaDescription,      noIndex,      ogImage{ alt, asset, "lqip": asset->metadata.lqip, "aspectRatio": asset->metadata.dimensions.aspectRatio }    }  }
export type POST_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
    lqip: string | null;
    aspectRatio: number | null;
  } | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href: string | null;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset: SanityImageAssetReference | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "contentImage";
    _key: string;
    lqip: string | null;
    aspectRatio: number | null;
    markDefs: null;
  }> | null;
  author: {
    name: string | null;
    role: string | null;
    image: {
      alt: string | null;
      asset: SanityImageAssetReference | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    ogImage: {
      alt: string | null;
      asset: SanityImageAssetReference | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
} | null;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now()]{    "slug": slug.current  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../web/apps/web/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: {    "settings": *[_type == "siteSettings" && _id == "siteSettings"][0]{ url },    "posts": *[_type == "post" && defined(slug.current) && publishedAt <= now()]{      "slug": slug.current,      "updatedAt": coalesce(_updatedAt, publishedAt)    }  }
export type SITEMAP_QUERY_RESULT = {
  settings: {
    url: string | null;
  } | null;
  posts: Array<{
    slug: string | null;
    updatedAt: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"siteSettings\" && _id == \"siteSettings\"][0]{\n    name,\n    url,\n    email,\n    tagline,\n    positioning,\n    keywords,\n    schedulingUrl,\n    ctaLabel,\n    ctaLabelShort,\n    serviceTypes,\n    navLinks[]{ _key, label, href }\n  }\n": SITE_SETTINGS_QUERY_RESULT;
    "\n  *[_type == \"homePage\" && _id == \"homePage\"][0]{\n    hero{\n      badge,\n      headline,\n      headlineAccent,\n      lede,\n      secondaryAction{ label, href },\n      trustPoints,\n      photo{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio },\n      photoCaption\n    },\n    problem{\n      eyebrow,\n      heading,\n      lede,\n      symptoms,\n      diagnosis,\n      diagnosisAccent\n    },\n    capabilities{\n      eyebrow,\n      heading,\n      lede,\n      capabilities[]{ _key, icon, title, description }\n    },\n    industries{\n      eyebrow,\n      heading,\n      industries\n    },\n    differentiators{\n      eyebrow,\n      headingLines,\n      headingAccent,\n      body,\n      differentiators[]{ _key, icon, label }\n    },\n    process{\n      eyebrow,\n      heading,\n      lede,\n      steps[]{ _key, icon, title, description }\n    },\n    assessment{\n      eyebrow,\n      heading,\n      lede,\n      price,\n      priceNote,\n      deliverablesHeading,\n      deliverables,\n      outcomeHeading,\n      outcome,\n      commitmentHeadline,\n      commitmentBody,\n      priceRange{ minPrice, maxPrice, currency }\n    },\n    caseStudy{\n      eyebrow,\n      heading,\n      lede,\n      disclaimer,\n      blocks[]{ _key, label, body },\n      metrics[]{ _key, value, label }\n    },\n    faq{\n      eyebrow,\n      heading,\n      questions[]{ _key, question, answer }\n    },\n    closingCta{\n      headline,\n      headlineAccent,\n      body,\n      emailPrompt\n    },\n    seo{\n      metaTitle,\n      metaDescription,\n      noIndex,\n      ogImage{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio }\n    }\n  }\n": HOME_PAGE_QUERY_RESULT;
    "\n  *[_type == \"blogPage\" && _id == \"blogPage\"][0]{\n    eyebrow,\n    heading,\n    lede,\n    emptyStateMessage,\n    seo{\n      metaTitle,\n      metaDescription,\n      noIndex,\n      ogImage{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio }\n    }\n  }\n": BLOG_PAGE_QUERY_RESULT;
    "\n  *[_type == \"post\" && defined(slug.current) && publishedAt <= now()]\n    | order(publishedAt desc){\n      _id,\n      title,\n      \"slug\": slug.current,\n      excerpt,\n      publishedAt,\n      coverImage{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio },\n      author->{ name, role },\n      categories[]->{ _id, title, \"slug\": slug.current }\n    }\n": POSTS_INDEX_QUERY_RESULT;
    "\n  *[_type == \"post\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    coverImage{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio },\n    body[]{\n      ...,\n      _type == \"contentImage\" => {\n        alt,\n        caption,\n        asset,\n        \"lqip\": asset->metadata.lqip,\n        \"aspectRatio\": asset->metadata.dimensions.aspectRatio\n      },\n      markDefs[]{ ..., _type == \"link\" => { href } }\n    },\n    author->{ name, role, image{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio } },\n    categories[]->{ _id, title, \"slug\": slug.current },\n    seo{\n      metaTitle,\n      metaDescription,\n      noIndex,\n      ogImage{ alt, asset, \"lqip\": asset->metadata.lqip, \"aspectRatio\": asset->metadata.dimensions.aspectRatio }\n    }\n  }\n": POST_DETAIL_QUERY_RESULT;
    "\n  *[_type == \"post\" && defined(slug.current) && publishedAt <= now()]{\n    \"slug\": slug.current\n  }\n": POST_SLUGS_QUERY_RESULT;
    "\n  {\n    \"settings\": *[_type == \"siteSettings\" && _id == \"siteSettings\"][0]{ url },\n    \"posts\": *[_type == \"post\" && defined(slug.current) && publishedAt <= now()]{\n      \"slug\": slug.current,\n      \"updatedAt\": coalesce(_updatedAt, publishedAt)\n    }\n  }\n": SITEMAP_QUERY_RESULT;
  }
}

